# Generated by Django 3.0.9 on 2021-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_remove_race_enable_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='annual',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
