# Generated by Django 3.0.14 on 2021-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0008_auto_20210321_1908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
