# Generated by Django 3.0.14 on 2021-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0009_auto_20210612_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
