# Generated by Django 3.0.14 on 2021-06-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0010_report_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racer",
            name="contact",
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
