# Generated by Django 3.0.14 on 2021-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0012_remove_racer_shirt_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Suggested value automatically generated from title and annual. Must be unique.",
                unique=True,
            ),
        ),
    ]
