# Generated by Django 3.0.14 on 2021-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0014_auto_20210612_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="bib_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
