# Generated by Django 3.0.14 on 2021-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0016_auto_20210612_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="ultrasignup_id",
            field=models.CharField(
                blank=True,
                help_text="This should be the ID of your UltraSignup.com ?did=",
                max_length=50,
                null=True,
            ),
        ),
    ]
