# Generated by Django 3.2.4 on 2021-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0018_result_import_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                (
                    "races",
                    models.ManyToManyField(related_name="series", to="races.Race"),
                ),
            ],
            options={
                "verbose_name": "Series",
                "verbose_name_plural": "Series",
            },
        ),
    ]
