# Generated by Django 3.2.18 on 2023-03-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flickr", "0006_photo_tags"),
        ("races", "0020_auto_20230308_2336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="background",
            field=models.ForeignKey(
                blank=True,
                help_text="The background image is used on the homepage. If a background image is not provided, the logo image will be used.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flickr.photo",
            ),
        ),
    ]
