# Generated by Django 4.2.11 on 2025-08-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0021_alter_race_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='background',
        ),
    ]
