# Generated by Django 5.2.11 on 2026-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0026_rename_gender_text_to_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='cut_off',
            field=models.CharField(blank=True, help_text='eg: 13 hours', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(blank=True, help_text='eg 26.2', max_length=200, null=True),
        ),
    ]
