# Generated by Django 4.2.11 on 2025-08-23 00:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_event_races'), ('events', '0003_auto_20200816_0929'), ('events', '0004_remove_event_enable_comments'), ('events', '0005_auto_20210612_1140')]

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Public')], default=2, verbose_name='status')),
                ('facebook_url', models.URLField(blank=True, help_text='Link to Facebook page', null=True)),
                ('facebook_event_url', models.URLField(blank=True, help_text='Link to Facebook Event page', null=True)),
                ('races', models.ManyToManyField(related_name='events', to='races.race')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
            bases=(models.Model, core.models.ShortUrlMixin),
        ),
    ]
