# Generated by Django 4.2.11 on 2025-08-23 00:14

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('runs', '0001_initial'), ('runs', '0002_auto_20200816_0929'), ('runs', '0003_remove_run_enable_comments'), ('runs', '0004_run_leaders'), ('runs', '0005_remove_run_contact')]

    dependencies = [
        ('members', '0001_initial'),
        ('members', '0005_auto_20200815_2351'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('run_time', models.CharField(help_text='Time of run (ex. 6:30 PM)', max_length=25)),
                ('details', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('leaders', models.ManyToManyField(blank=True, related_name='runs', to='members.member')),
            ],
            options={
                'ordering': ['day_of_week'],
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
            },
            bases=(models.Model, core.models.ShortUrlMixin),
        ),
    ]
