# Generated by Django 4.2.11 on 2024-04-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_leaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='contact',
        ),
    ]
