x-common-settings: &common-settings
  build:
    context: .
    dockerfile: .dockerfiles/Dockerfile
    target: release
  env_file:
    - .env
  entrypoint: /bin/chamber exec trailhawks/production --
  environment:
    - "DJANGO_SETTINGS_MODULE=config.settings_trailhawks"
  volumes:
    - django-media:/src/media
    - django-static:/src/static

services:

  web:
    <<: *common-settings
    # command: uv run gunicorn config.wsgi --bind 0.0.0.0:8000 --workers=2
    command: uwsgi --buffer-size=8196 --chdir=/src --enable-threads --harakiri=180 --http-socket=:8000 --http-timeout=180 --log-x-forwarded-for --master --max-requests=5000 --module=config.wsgi --need-app --offload-threads=2 --post-buffering=4096 --processes=1 --static-map=/media=/src/media_root --strict --threads=2 --thunder-lock --vacuum
    expose:
      - 8000

volumes:
  django-media:
  django-static:
