x-common-settings: &common-settings
  build:
    context: .
    dockerfile: .dockerfiles/Dockerfile
  env_file:
    - .env
  entrypoint: /src/compose-entrypoint.sh
  volumes:
    - django-media:/src/media
    - django-static:/src/static

services:

  web:
    <<: *common-settings
    command: /src/start-web.sh
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings_trailhawks"
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  hawkhundred:
    <<: *common-settings
    command: /src/start-web.sh
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings_hawkhundred"
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  django-media:
  django-static:
