version: "3.3"

services:

  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    container_name: trailhawks
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ".env"
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings_trailhawks"
    ports:
      - 8000:8000
    volumes:
      - .:/src
      - ./media_root:/src/media_root
      - ./static_root:/src/static_root

  hawkhundred:
    container_name: hawkhundred
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ".env"
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings_hawkhundred"
    ports:
      - 8010:8000
    volumes:
      - .:/src
      - ./media_root:/src/media_root
      - ./static_root:/src/static_root

volumes:
  postgres-data:
