name: Deploy latest main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Publish Production Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install bumpver
        run: |
          python -m pip install --upgrade pip
          python -m pip install bumpver

      - name: Configure git to push
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Automated Publisher"

      - name: Bump Version
        id: vars
        run: |
          bumpver update
          eval $(bumpver show --env)
          echo "name=current_version" >> $CURRENT_VERSION

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Production Docker image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: .docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.current_version }}

      - name: Push Release Build to GitHub
        run: |
          git push
